/* eslint-disable @typescript-eslint/no-explicit-any */
import { Head, router } from '@inertiajs/react';
import { Banknote, Boxes, PackageCheck, Search, ShieldCheck, Warehouse } from 'lucide-react';
import { useMemo, useState } from 'react';
import AppLayout from '../../layouts/AppLayout';

const number = (value: number) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 3 }).format(value);
const money = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);

export default function Index({ stocks, warehouses, selectedWarehouse, canViewAll, summary }: any) {
  const [search, setSearch] = useState('');
  const rows = useMemo(() => stocks.filter((row: any) => `${row.item.code} ${row.item.name} ${row.batch_no || ''} ${row.warehouse.name}`.toLowerCase().includes(search.toLowerCase())), [stocks, search]);

  return <AppLayout title="Stok Gudang"><Head title="Stok Gudang"/>
    <section className="relative mb-6 overflow-hidden rounded-3xl bg-[#10233f] px-6 py-7 text-white shadow-xl shadow-slate-200 sm:px-8"><div className="absolute -right-16 -top-24 size-64 rounded-full bg-emerald-400/15 blur-3xl"/><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.07] px-3 py-1.5 text-xs text-emerald-300"><ShieldCheck size={14}/>{canViewAll ? 'Akses seluruh gudang' : 'Akses gudang/unit akun Anda'}</span><h2 className="mt-4 text-2xl font-semibold">Saldo persediaan terkini</h2><p className="mt-2 max-w-xl text-sm text-slate-400">Pantau stok fisik, reservasi, saldo tersedia, batch, kedaluwarsa, dan nilai persediaan.</p></div>{canViewAll&&<label className="text-xs font-semibold text-slate-300"><span className="mb-2 block">Filter gudang</span><select value={selectedWarehouse||''} onChange={e=>router.get('/warehouse-stocks',e.target.value?{warehouse_id:e.target.value}:{},{preserveState:true,replace:true})} className="h-11 min-w-64 rounded-xl border border-white/10 bg-white/10 px-3 text-sm text-white outline-none"><option className="text-slate-900" value="">Semua gudang</option>{warehouses.map((x:any)=><option className="text-slate-900" key={x.id} value={x.id}>{x.name}</option>)}</select></label>}</div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Baris stok',number(summary.items),Boxes,'bg-blue-50 text-blue-600'],['Stok fisik',number(summary.onHand),Warehouse,'bg-emerald-50 text-emerald-600'],['Tersedia',number(summary.available),PackageCheck,'bg-violet-50 text-violet-600'],['Nilai persediaan',money(summary.value),Banknote,'bg-amber-50 text-amber-600'],
    ].map(([label,value,Icon,tone]:any)=><div key={label} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon size={19}/></div><p className="mt-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold text-slate-950">{value}</p></div>)}</section>

    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold text-slate-950">Detail stok per batch</h3><p className="mt-1 text-sm text-slate-500">Menampilkan {rows.length} baris persediaan.</p></div><label className="relative"><Search size={17} className="absolute left-3.5 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari item, batch, gudang..." className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-4 text-sm outline-none focus:border-emerald-400 sm:w-72"/></label></div>
      {rows.length?<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50/80 text-left text-[11px] uppercase tracking-[.1em] text-slate-500"><tr>{['Gudang / lokasi','Item','Batch / kedaluwarsa','Stok fisik','Reservasi','Tersedia','HPP','Nilai'].map(x=><th key={x} className="whitespace-nowrap px-5 py-3.5">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row:any)=><tr key={row.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><b>{row.warehouse.name}</b><small className="mt-1 block text-slate-400">{row.location?`${row.location.code} · ${row.location.name}`:'Lokasi belum ditentukan'}</small></td><td className="px-5 py-4"><b>{row.item.name}</b><small className="mt-1 block text-slate-400">{row.item.code} · {row.item.base_uom}</small></td><td className="whitespace-nowrap px-5 py-4 text-slate-600">{row.batch_no||'-'}<small className="mt-1 block text-slate-400">{row.expired_at||'Tanpa kedaluwarsa'}</small></td><td className="px-5 py-4 font-semibold">{number(row.qty_on_hand)}</td><td className="px-5 py-4 text-amber-600">{number(row.qty_reserved)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${row.qty_available<=0?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{number(row.qty_available)}</span></td><td className="whitespace-nowrap px-5 py-4">{money(row.average_cost)}</td><td className="whitespace-nowrap px-5 py-4 font-semibold">{money(row.stock_value)}</td></tr>)}</tbody></table></div>:<div className="px-6 py-16 text-center"><Boxes className="mx-auto text-slate-300"/><p className="mt-3 font-medium text-slate-600">Stok tidak ditemukan</p></div>}
    </section>
  </AppLayout>;
}
